import { entityIds } from "./entityIds";
import { getEntityGeoPosition } from "./geoPositions";
import type { EntityKind, EntityStats, MapEntity } from "./types";

const village = "/images/history/mountains.jpg";

function stats(
  relations: number,
  heroes: number,
  events: number,
  landmarks: number,
  sources: number,
): EntityStats {
  return { relations, heroes, events, landmarks, sources };
}

function place(
  id: string,
  name: string,
  caption: string,
  subtitle: string,
  summary: string,
  counts: EntityStats,
  x: number,
  y: number,
  image = "",
): MapEntity {
  return {
    id,
    kind: "place",
    name,
    caption,
    subtitle,
    summary,
    image,
    stats: counts,
    x,
    y,
    description: summary,
    coordinates: getEntityGeoPosition(id),
  };
}

function feature(
  id: string,
  kind: EntityKind,
  name: string,
  caption: string,
  x: number,
  y: number,
): MapEntity {
  return {
    id,
    kind,
    name,
    caption,
    subtitle: name,
    summary: `Историческая связь: ${name}.`,
    image: "",
    stats: stats(8, 2, 3, 2, 4),
    x,
    y,
    description: `Подтверждённый объект атласа: ${name}.`,
    coordinates: getEntityGeoPosition(id),
  };
}

export const mapEntities: MapEntity[] = [
  place(
    entityIds.grozny,
    "Грозный",
    "столица региона",
    "Столица Чеченской Республики",
    "Крупнейший город на Северном Кавказе. Основан в 1818 году.",
    stats(128, 45, 32, 24, 67),
    40,
    38,
    "/images/history/grozny.jpg",
  ),
  place(
    entityIds.shelkovskaya,
    "Шелковская",
    "станица",
    "Станица на севере республики",
    "Историческая казачья станица на левом берегу Терека.",
    stats(21, 6, 5, 4, 9),
    33,
    12,
  ),
  place(
    entityIds.naurskaya,
    "Наурская",
    "станица",
    "Административный центр Наурского района",
    "Одно из старейших поселений терского левобережья.",
    stats(18, 5, 4, 3, 8),
    58,
    10,
  ),
  place(
    entityIds.shali,
    "Шали",
    "город",
    "Город в центральной части республики",
    "Один из крупнейших населённых пунктов Чеченской равнины.",
    stats(34, 11, 8, 6, 14),
    40,
    30,
  ),
  place(
    entityIds.vedeno,
    "Ведено",
    "районный центр",
    "Село в горной части республики",
    "Историческая резиденция и центр Веденского района.",
    stats(27, 9, 12, 8, 22),
    71,
    22,
  ),
  place(
    entityIds.kurchaloy,
    "Курчалой",
    "город",
    "Административный центр Курчалоевского района",
    "Город на юго-востоке Чеченской равнины.",
    stats(23, 7, 9, 4, 11),
    63,
    34,
  ),
  place(
    entityIds.itumKali,
    "Итум-Кали",
    "село",
    "Село в Аргунском ущелье",
    "Родовые башни и средневековые памятники горной Чечни.",
    stats(19, 4, 6, 14, 12),
    84,
    20,
  ),
  place(
    entityIds.urusMartan,
    "Урус-Мартан",
    "город",
    "Административный центр Урус-Мартановского района",
    "Крупный город на западе Чеченской равнины.",
    stats(29, 10, 11, 5, 13),
    27,
    53,
  ),
  place(
    entityIds.argun,
    "Аргун",
    "город",
    "Город на реке Аргун",
    "Промышленный город рядом с Грозным.",
    stats(26, 13, 7, 5, 10),
    62,
    55,
  ),
  place(
    entityIds.nozhayYurt,
    "Ножай-Юрт",
    "село",
    "Село в Ножай-Юртовском районе",
    "Расположено на левом берегу реки Аргун.",
    stats(36, 12, 9, 7, 16),
    58,
    73,
    village,
  ),
  place(
    entityIds.shatoy,
    "Шатой",
    "село",
    "Село в Аргунском ущелье",
    "Исторический центр горного Шатойского района.",
    stats(17, 5, 6, 9, 11),
    44,
    62,
  ),
  place(
    entityIds.benoy,
    "Беной",
    "село",
    "Село в Ножай-Юртовском районе",
    "Родовое село тайпа беной, узел местной истории.",
    stats(22, 8, 6, 10, 13),
    66,
    82,
  ),
  place(
    entityIds.tsentaroy,
    "Центарой",
    "село",
    "Село в Курчалоевском районе",
    "Пример связи места и исторического события.",
    stats(20, 9, 10, 4, 9),
    80,
    66,
  ),
  place(
    entityIds.achkhoyMartan,
    "Ачхой-Мартан",
    "село",
    "Административный центр Ачхой-Мартановского района",
    "Село на западе республики у Ассинского ущелья.",
    stats(18, 6, 5, 6, 8),
    18,
    66,
  ),
  place(
    entityIds.gudermes,
    "Гудермес",
    "город",
    "Второй по величине город республики",
    "Крупный транспортный узел на востоке Чечни.",
    stats(41, 14, 12, 7, 19),
    78,
    40,
  ),
  place(
    entityIds.znamenskoye,
    "Знаменское",
    "село",
    "Административный центр Надтеречного района",
    "Село на правом берегу Терека с богатым архивом.",
    stats(16, 4, 4, 3, 15),
    20,
    24,
  ),
  feature(
    entityIds.akhmadKadyrov,
    "person",
    "Ахмат-Хаджи Кадыров",
    "личность",
    34,
    62,
  ),
  feature(entityIds.tower, "landmark", "Башня", "памятник", 23, 58),
  feature(
    entityIds.historicMosque,
    "landmark",
    "Мечеть XIX века",
    "памятник",
    54,
    67,
  ),
  feature(
    entityIds.publicEducation,
    "event",
    "Народное образование",
    "событие",
    73,
    70,
  ),
  feature(entityIds.constitution, "event", "Конституция ЧР", "событие", 57, 82),
  feature(
    entityIds.republicRestoration,
    "event",
    "Восстановление республики",
    "событие",
    82,
    62,
  ),
  feature(
    entityIds.archiveCollection,
    "source",
    "Архивная коллекция",
    "источник",
    65,
    48,
  ),
];
