import { entityIds as id } from "./entityIds";
import type { Relation } from "./types";

export const mapRelations: Relation[] = [
  { from: id.grozny, to: id.shali },
  { from: id.grozny, to: id.argun },
  { from: id.grozny, to: id.gudermes },
  { from: id.grozny, to: id.urusMartan },
  { from: id.grozny, to: id.kurchaloy },
  { from: id.grozny, to: id.shelkovskaya },
  { from: id.grozny, to: id.naurskaya },
  { from: id.grozny, to: id.vedeno },
  { from: id.grozny, to: id.znamenskoye },
  { from: id.shali, to: id.argun },
  { from: id.shali, to: id.shatoy },
  { from: id.argun, to: id.shatoy },
  { from: id.argun, to: id.tsentaroy },
  { from: id.kurchaloy, to: id.vedeno },
  { from: id.kurchaloy, to: id.gudermes },
  { from: id.gudermes, to: id.tsentaroy },
  { from: id.vedeno, to: id.itumKali },
  { from: id.shatoy, to: id.itumKali },
  { from: id.shatoy, to: id.nozhayYurt },
  { from: id.nozhayYurt, to: id.benoy },
  { from: id.nozhayYurt, to: id.tsentaroy },
  { from: id.urusMartan, to: id.achkhoyMartan },
  { from: id.urusMartan, to: id.shatoy },
  { from: id.shelkovskaya, to: id.naurskaya },
  { from: id.naurskaya, to: id.znamenskoye },
  { from: id.grozny, to: id.akhmadKadyrov },
  { from: id.grozny, to: id.tower },
  { from: id.grozny, to: id.historicMosque },
  { from: id.grozny, to: id.publicEducation },
  { from: id.grozny, to: id.archiveCollection },
  { from: id.akhmadKadyrov, to: id.constitution },
  { from: id.akhmadKadyrov, to: id.republicRestoration },
];
