"""Кураторский слой конкретных документов и утверждений о Чечне.

В отличие от массового импорта Wikidata, каждая цитата здесь указывает,
какое именно утверждение поддерживает конкретная страница или документ.
"""

SOURCES = [
    {"slug": "archive_chr", "title": "Архивное управление Правительства ЧР",
     "publisher": "Правительство Чеченской Республики", "url": "https://arhiv-chr.ru/",
     "source_type": "official", "reliability": "high",
     "notes": "Официальные архивные публикации и электронная библиотека."},
    {"slug": "chechen_museum", "title": "Музей Чеченской Республики",
     "publisher": "ГБУК «Музей Чеченской Республики»", "url": "https://chechenmuseum.ru/",
     "source_type": "museum", "reliability": "high"},
    {"slug": "presidential_library", "title": "Президентская библиотека имени Б. Н. Ельцина",
     "publisher": "Президентская библиотека", "url": "https://www.prlib.ru/",
     "source_type": "official", "reliability": "high"},
    {"slug": "rsl", "title": "Российская государственная библиотека",
     "publisher": "РГБ", "url": "https://search.rsl.ru/", "source_type": "official",
     "reliability": "high"},
    {"slug": "historyrussia", "title": "Электронная библиотека исторических документов",
     "publisher": "Исторический факультет МГУ", "url": "https://www.historyrussia.org/",
     "source_type": "academic", "reliability": "high"},
    {"slug": "chechnya_law", "title": "Нормативные акты Чеченской Республики",
     "publisher": "Региональное законодательство", "url": "https://chechnya-gov.ru/",
     "source_type": "official", "reliability": "high"},
    {"slug": "pamyat_naroda", "title": "Память народа",
     "publisher": "Министерство обороны Российской Федерации",
     "url": "https://pamyat-naroda.ru/", "source_type": "official", "reliability": "high",
     "notes": "Подлинники документов ЦАМО и других военных архивов."},
    {"slug": "osm", "title": "OpenStreetMap",
     "publisher": "OpenStreetMap contributors", "url": "https://www.openstreetmap.org/",
     "source_type": "dataset", "reliability": "medium",
     "notes": "Независимое координатное свидетельство; требует проверки редактором."},
]

DOCUMENTS = [
    {"slug": "archive-history", "source": "archive_chr", "title": "История архива",
     "repository": "Архивное управление Правительства ЧР", "document_type": "archive_guide",
     "url": "https://arhiv-chr.ru/ob-arkhivnom-upravlenii/archive-history",
     "publication_year": 2016, "verification_status": "verified",
     "notes": "О составе и потерях архивных фондов, депортации и истории архивного дела."},
    {"slug": "mansur-letters", "source": "archive_chr", "title": "Письма времен шейха Мансура",
     "repository": "Архивное управление Правительства ЧР", "document_type": "archival_publication",
     "url": "https://arhiv-chr.ru/deyatelnost/publikatsii/3-pisma-vremen-shejkha-mansura",
     "verification_status": "verified"},
    {"slug": "kunta-archive", "source": "archive_chr", "title": "Мученики за веру",
     "repository": "Архивное управление Правительства ЧР", "document_type": "archival_publication",
     "url": "https://www.arhiv-chr.ru/en/deyatelnost/publikatsii/4-mucheniki-za-veru",
     "verification_status": "verified"},
    {"slug": "archive-library", "source": "archive_chr", "title": "Электронная библиотека",
     "repository": "Архивное управление Правительства ЧР", "document_type": "catalog",
     "url": "https://arhiv-chr.ru/elektronnaya-biblioteka", "verification_status": "verified"},
    {"slug": "prlib-chechnya-collection", "source": "presidential_library",
     "title": "Чеченская Республика: страницы истории", "repository": "Президентская библиотека",
     "document_type": "digital_collection", "url": "https://www.prlib.ru/collections/1973265",
     "verification_status": "verified"},
    {"slug": "berger-1859", "source": "presidential_library", "title": "Чечня и чеченцы",
     "repository": "Президентская библиотека", "document_type": "historical_book",
     "url": "https://www.prlib.ru/item/462827", "publication_year": 1859,
     "verification_status": "verified"},
    {"slug": "chechen-archive-v2", "source": "rsl", "title": "Чеченский архив. Том 2",
     "repository": "Российская государственная библиотека", "document_type": "bibliographic_record",
     "url": "https://search.rsl.ru/ru/record/01006539819", "verification_status": "verified"},
    {"slug": "national-archive-index", "source": "historyrussia",
     "title": "Национальный архив Чеченской Республики: указатель",
     "repository": "Электронная библиотека исторических документов", "document_type": "archive_index",
     "url": "https://www.newspapers.historyrussia.org/ru/indexes/values/1078427?view=list",
     "verification_status": "verified"},
    {"slug": "museum-six-heroes", "source": "chechen_museum",
     "title": "Чеченцы — Герои Советского Союза", "repository": "Музей ЧР",
     "document_type": "museum_lecture",
     "url": "https://chechenmuseum.ru/news/lektsiya-chechentsy-geroi-sovetskogo-sojuza",
     "verification_status": "corroborated"},
    {"slug": "museum-visaitov", "source": "chechen_museum", "title": "Мовлид Алероевич Висаитов",
     "repository": "Музей ЧР", "document_type": "museum_lecture",
     "url": "https://chechenmuseum.ru/news/urok-muzhestva-geroj-sovetskogo-sojuza-movlid-aleroevich-visaitov",
     "verification_status": "corroborated"},
    {"slug": "museum-nuradilov", "source": "chechen_museum", "title": "Ханпаша Нурадилович Нурадилов",
     "repository": "Музей ЧР", "document_type": "museum_lecture",
     "url": "https://chechenmuseum.ru/news/lektsiya-geroj-sovetskogo-sojuza-nuradilov-hanpasha-nuradilovich",
     "verification_status": "corroborated"},
    {"slug": "museum-taimiev", "source": "chechen_museum",
     "title": "Военно-политическая деятельность Бейбулата Таймиева (1779–1831)",
     "repository": "Музей ЧР", "document_type": "museum_lecture",
     "url": "https://chechenmuseum.ru/news/voenno-politicheskaya-deyatelnost-bejbulata-tajmieva-1779-1831-gg",
     "verification_status": "corroborated"},
    {"slug": "warheroes-visaitov", "source": "warheroes", "title": "Висаитов Мовлид Алероевич",
     "repository": "Герои страны", "document_type": "biographical_profile",
     "url": "https://www.warheroes.ru/hero/hero.asp?Hero_id=659", "verification_status": "corroborated"},
    {"slug": "warheroes-nuradilov", "source": "warheroes", "title": "Нурадилов Ханпаша Нурадилович",
     "repository": "Герои страны", "document_type": "biographical_profile",
     "url": "https://warheroes.ru/hero/hero.asp?Hero_id=2636", "verification_status": "corroborated"},
    {"slug": "warheroes-idrisov", "source": "warheroes", "title": "Идрисов Абухаджи",
     "repository": "Герои страны", "document_type": "biographical_profile",
     "url": "https://posta.warheroes.ru/hero/hero.asp?Hero_id=5755", "verification_status": "corroborated"},
    {"slug": "warheroes-beybulatov", "source": "warheroes", "title": "Байбулатов Ирбайхан Адылханович",
     "repository": "Герои страны", "document_type": "biographical_profile",
     "url": "https://warheroes.ru/hero/hero.asp?Hero_id=5744", "verification_status": "corroborated"},
    {"slug": "warheroes-mirzoev", "source": "warheroes", "title": "Мухамед-Мирзаев Хаваджи",
     "repository": "Герои страны", "document_type": "biographical_profile",
     "url": "https://warheroes.ru/hero/hero.asp?Hero_id=4476", "verification_status": "corroborated"},
    {"slug": "warheroes-dachiev", "source": "warheroes", "title": "Дачиев Хансултан Чапаевич",
     "repository": "Герои страны", "document_type": "biographical_profile",
     "url": "https://warheroes.ru/hero/hero.asp?Hero_id=4396", "verification_status": "corroborated"},
    {"slug": "law-achkhoy-city", "source": "chechnya_law",
     "title": "Закон ЧР от 06.02.2023 № 1-РЗ о преобразовании села Ачхой-Мартан",
     "repository": "Законодательство Чеченской Республики", "document_type": "law",
     "url": "https://chechnya-gov.ru/doc/8981", "publication_year": 2023,
     "archive_reference": "№ 1-РЗ", "verification_status": "verified"},
    {"slug": "law-sernovodsk-district", "source": "chechnya_law",
     "title": "Закон о переименовании Сунженского района в Серноводский район",
     "repository": "Законодательство Чеченской Республики", "document_type": "law",
     "url": "https://chechnya-gov.ru/doc/6789", "publication_year": 2019,
     "verification_status": "verified"},
    {"slug": "law-sernovodsk-city", "source": "chechnya_law",
     "title": "Закон ЧР от 28.02.2024 № 9-РЗ о преобразовании села Серноводское",
     "repository": "Гарант: региональное законодательство", "document_type": "law",
     "url": "https://base.garant.ru/408622415/", "publication_year": 2024,
     "archive_reference": "№ 9-РЗ", "verification_status": "verified"},
]

CITATIONS = [
    ("event", "deportation-1944", "archive-history", "23 февраля 1944 года чеченцы были выселены в Казахстан и Среднюю Азию; ЧИАССР ликвидирована.", "verified"),
    ("event", "mansur-uprising", "mansur-letters", "Архивная публикация содержит письма и донесения времени движения шейха Мансура.", "verified"),
    ("person", "sheikh-mansur", "mansur-letters", "Шейх Мансур находился в Алдах; публикация передаёт документальные свидетельства эпохи.", "verified"),
    ("person", "beybulat-taimiev", "museum-taimiev", "Музейная лекция датирует жизнь 1779–1831 и описывает военно-политическую деятельность.", "corroborated"),
    ("person", "visaitov", "warheroes-visaitov", "Фактическая дата рождения — 13 мая 1914 года; 1913 год был указан им для поступления в полковую школу.", "corroborated"),
    ("person", "visaitov", "museum-visaitov", "Командовал 28-м гвардейским кавалерийским полком, вышел к Эльбе и получил звание Героя посмертно 5 мая 1990 года.", "corroborated"),
    ("event", "elbe-meeting", "museum-visaitov", "Полк Висаитова к исходу 2 мая 1945 года вышел к Эльбе и встретился с союзными войсками.", "corroborated"),
    ("person", "nuradilov", "warheroes-nuradilov", "Даты жизни 6 июля 1920 — 12 сентября 1942; профиль описывает боевой путь.", "corroborated"),
    ("person", "nuradilov", "museum-nuradilov", "Музей приводит итог: до 920 уничтоженных, 12 пленных и 7 захваченных пулемётов.", "corroborated"),
    ("person", "idrisov", "warheroes-idrisov", "Профиль приводит даты жизни и результат снайпера — 349 к марту 1944 года.", "corroborated"),
    ("person", "beybulatov", "warheroes-beybulatov", "В боях за Мелитополь батальон отразил 19 контратак; звание присвоено посмертно 1 ноября 1943 года.", "corroborated"),
    ("person", "magomed-mirzoev", "warheroes-mirzoev", "Родился в 1910 году в Алхазурово; отличился при форсировании Днепра и умер от ран 4 октября 1943 года.", "corroborated"),
    ("person", "dachiev", "warheroes-dachiev", "Родился 12 декабря 1922 года в Герзель-Ауле; в сентябре 1943 года доставил разведданные о немецкой обороне за Днепром.", "corroborated"),
    ("place", "achkhoy-martan", "law-achkhoy-city", "Село преобразовано в городской населённый пункт — город Ачхой-Мартан.", "verified"),
    ("place", "sernovodskoye", "law-sernovodsk-city", "Село Серноводское преобразовано в городской населённый пункт — город Серноводское.", "verified"),
    ("event", "caucasian-war", "berger-1859", "Книга 1859 года — исторический источник о Чечне и чеченцах периода Кавказской войны.", "corroborated"),
]
