import { MOCK_ENTITY_IDS as id } from "./entityIds";
import type { EntitySeed } from "./types";

export const catalogSeeds = [
  {
    id: id.shelkovskaya,
    type: "settlement",
    slug: "shelkovskaya",
    title: "Шелковская",
    shortDescription: "Историческая станица на левом берегу Терека.",
    fullDescription:
      "Шелковская развивалась как важный населённый пункт северной равнины, связанный с речными путями, земледелием и историей терского левобережья.",
    coordinates: { latitude: 43.508, longitude: 46.34 },
    periodFrom: 1710,
    relations: 21,
    sourceTitle: "Материалы по истории Шелковской",
  },
  {
    id: id.naurskaya,
    type: "settlement",
    slug: "naurskaya",
    title: "Наурская",
    shortDescription: "Одно из старейших поселений терского левобережья.",
    fullDescription:
      "Наурская сохраняет историю северных поселений Чечни, где пересекались торговые маршруты, сельское хозяйство и административная жизнь района.",
    coordinates: { latitude: 43.651, longitude: 45.311 },
    periodFrom: 1642,
    relations: 18,
    sourceTitle: "Наурская в региональных архивах",
  },
  {
    id: id.shali,
    type: "settlement",
    slug: "shali",
    title: "Шали",
    shortDescription: "Крупный город в центральной части республики.",
    fullDescription:
      "Шали — исторический центр Чеченской равнины, в городской памяти которого соединены традиции местных сообществ и современное развитие.",
    coordinates: { latitude: 43.149, longitude: 45.901 },
    periodFrom: 1200,
    relations: 34,
    sourceTitle: "Историко-краеведческие материалы о Шали",
  },
  {
    id: id.vedeno,
    type: "settlement",
    slug: "vedeno",
    title: "Ведено",
    shortDescription: "Исторический центр горной части республики.",
    fullDescription:
      "Ведено связано с ключевыми страницами истории горной Чечни и служит точкой входа к исследованию поселений Веденского района.",
    coordinates: { latitude: 42.969, longitude: 46.099 },
    periodFrom: 1200,
    relations: 27,
    sourceTitle: "Документы Веденского района",
  },
  {
    id: id.kurchaloy,
    type: "settlement",
    slug: "kurchaloy",
    title: "Курчалой",
    shortDescription: "Город на юго-востоке Чеченской равнины.",
    fullDescription:
      "Курчалой формировался как районный центр, объединяющий истории местных поселений, образовательных учреждений и общественной жизни.",
    coordinates: { latitude: 43.201, longitude: 46.089 },
    periodFrom: 1700,
    relations: 23,
    sourceTitle: "Курчалой: материалы районной истории",
  },
  {
    id: id.itumKali,
    type: "settlement",
    slug: "itum-kali",
    title: "Итум-Кали",
    shortDescription: "Село в Аргунском ущелье среди башенных комплексов.",
    fullDescription:
      "Итум-Кали раскрывает историю горной архитектуры, древних дорог и родовых поселений верховьев Аргуна.",
    coordinates: { latitude: 42.736, longitude: 45.575 },
    periodFrom: 1100,
    relations: 19,
    sourceTitle: "Наследие Итум-Калинского района",
  },
  {
    id: id.urusMartan,
    type: "settlement",
    slug: "urus-martan",
    title: "Урус-Мартан",
    shortDescription: "Крупный город на западе Чеченской равнины.",
    fullDescription:
      "Урус-Мартан хранит свидетельства развития западной части республики, её ремёсел, общественных институтов и семейных архивов.",
    coordinates: { latitude: 43.13, longitude: 45.542 },
    periodFrom: 1700,
    relations: 29,
    sourceTitle: "Летопись Урус-Мартана",
  },
  {
    id: id.argun,
    type: "settlement",
    slug: "argun",
    title: "Аргун",
    shortDescription: "Город на реке Аргун рядом с Грозным.",
    fullDescription:
      "Аргун вырос как транспортный и промышленный узел, сохранив связь с историей приаргунских поселений и городских сообществ.",
    coordinates: { latitude: 43.293, longitude: 45.872 },
    periodFrom: 1800,
    relations: 26,
    sourceTitle: "Аргун в документах XX века",
  },
  {
    id: id.shatoy,
    type: "settlement",
    slug: "shatoy",
    title: "Шатой",
    shortDescription: "Исторический центр Аргунского ущелья.",
    fullDescription:
      "Шатой связывает маршруты горных поселений, башенную архитектуру и устные предания центральной части Аргунского ущелья.",
    coordinates: { latitude: 42.872, longitude: 45.691 },
    periodFrom: 1200,
    relations: 17,
    sourceTitle: "Архив Шатойского района",
  },
  {
    id: id.benoy,
    type: "settlement",
    slug: "benoy",
    title: "Беной",
    shortDescription: "Историческое село Ножай-Юртовского района.",
    fullDescription:
      "Беной представлен как узел родовой и локальной памяти, связанный с горным ландшафтом и историей соседних поселений.",
    coordinates: { latitude: 42.942, longitude: 46.33 },
    periodFrom: 1200,
    relations: 22,
    sourceTitle: "Свидетельства о селе Беной",
  },
  {
    id: id.tsentaroy,
    type: "settlement",
    slug: "tsentaroy",
    title: "Центарой",
    shortDescription: "Село в Курчалоевском районе.",
    fullDescription:
      "Центарой включён в атлас как место пересечения семейных историй, общественных событий и развития восточной части республики.",
    coordinates: { latitude: 43.225, longitude: 46.169 },
    periodFrom: 1600,
    relations: 20,
    sourceTitle: "Краеведческие материалы о Центарое",
  },
  {
    id: id.achkhoyMartan,
    type: "settlement",
    slug: "achkhoy-martan",
    title: "Ачхой-Мартан",
    shortDescription: "Районный центр у Ассинского ущелья.",
    fullDescription:
      "Ачхой-Мартан объединяет истории западных поселений Чечни, речных долин и дорог, ведущих к предгорьям Кавказа.",
    coordinates: { latitude: 43.19, longitude: 45.283 },
    periodFrom: 1700,
    relations: 18,
    sourceTitle: "История Ачхой-Мартановского района",
  },
  {
    id: id.gudermes,
    type: "settlement",
    slug: "gudermes",
    title: "Гудермес",
    shortDescription: "Крупный транспортный узел восточной Чечни.",
    fullDescription:
      "Гудермес развивался вокруг дорог и железнодорожного сообщения, став одним из ключевых городских центров республики.",
    coordinates: { latitude: 43.351, longitude: 46.1 },
    periodFrom: 1700,
    relations: 41,
    sourceTitle: "Гудермес: город и железная дорога",
  },
  {
    id: id.znamenskoye,
    type: "settlement",
    slug: "znamenskoye",
    title: "Знаменское",
    shortDescription: "Село на правом берегу Терека.",
    fullDescription:
      "Знаменское сохраняет материалы по истории Надтеречного района, речных поселений и административных преобразований северной Чечни.",
    coordinates: { latitude: 43.678, longitude: 45.128 },
    periodFrom: 1800,
    relations: 16,
    sourceTitle: "Фонд истории Надтеречного района",
  },
  {
    id: id.akhmadKadyrov,
    type: "person",
    slug: "akhmad-khadzhi-kadyrov",
    title: "Ахмат-Хаджи Кадыров",
    shortDescription:
      "Государственный и религиозный деятель Чеченской Республики.",
    fullDescription:
      "Карточка объединяет опубликованные материалы о биографии Ахмат-Хаджи Кадырова, его общественной деятельности и связях с местами и событиями региона.",
    coordinates: null,
    periodFrom: 1951,
    periodTo: 2004,
    relations: 45,
    sourceType: "official_publication",
    sourceTitle: "Биографические материалы Ахмат-Хаджи Кадырова",
    coverUrl: "/images/history/akhmad-kadyrov.jpg",
    mediaWidth: 817,
    mediaHeight: 1089,
  },
  {
    id: id.tower,
    type: "landmark",
    slug: "mountain-tower",
    title: "Горная башня",
    shortDescription: "Образец традиционной башенной архитектуры Чечни.",
    fullDescription:
      "Башенные сооружения были частью оборонительного и жилого ландшафта горных обществ и остаются важными источниками архитектурной памяти.",
    coordinates: { latitude: 42.723, longitude: 45.574 },
    periodFrom: 1100,
    periodTo: 1700,
    relations: 8,
    sourceType: "scientific_article",
    sourceTitle: "Башенная архитектура горной Чечни",
  },
  {
    id: id.historicMosque,
    type: "landmark",
    slug: "historic-mosque-xix-century",
    title: "Мечеть XIX века",
    shortDescription: "Исторический памятник религиозной архитектуры.",
    fullDescription:
      "Мечеть представлена как свидетельство развития местной строительной традиции и духовной жизни поселения в XIX столетии.",
    coordinates: { latitude: 43.091, longitude: 46.376 },
    periodFrom: 1800,
    periodTo: 1899,
    relations: 8,
    sourceType: "museum_material",
    sourceTitle: "Паспорт памятника: мечеть XIX века",
  },
  {
    id: id.publicEducation,
    type: "event",
    slug: "public-education-development",
    title: "Развитие народного образования",
    shortDescription: "Этап формирования доступного общественного образования.",
    fullDescription:
      "Событие объединяет свидетельства открытия школ, работы учителей и распространения грамотности в населённых пунктах региона.",
    coordinates: null,
    periodFrom: 1860,
    periodTo: 1930,
    relations: 8,
    sourceType: "archive_document",
    sourceTitle: "Документы о народном образовании",
  },
  {
    id: id.constitution,
    type: "event",
    slug: "constitution-chechen-republic",
    title: "Принятие Конституции ЧР",
    shortDescription: "Республиканский референдум и принятие Конституции.",
    fullDescription:
      "Событие отражает принятие Конституции Чеченской Республики на референдуме и последующее формирование правовых институтов региона.",
    coordinates: null,
    periodFrom: 2003,
    periodTo: 2003,
    relations: 14,
    sourceType: "official_publication",
    sourceTitle: "Конституция Чеченской Республики",
  },
  {
    id: id.republicRestoration,
    type: "event",
    slug: "republic-restoration",
    title: "Восстановление республики",
    shortDescription:
      "Период восстановления общественной и городской инфраструктуры.",
    fullDescription:
      "Карточка объединяет опубликованные свидетельства восстановления населённых пунктов, учреждений и общественной жизни Чеченской Республики.",
    coordinates: null,
    periodFrom: 2000,
    periodTo: 2010,
    relations: 22,
    sourceType: "official_publication",
    sourceTitle: "Материалы о восстановлении Чеченской Республики",
  },
  {
    id: id.archiveCollection,
    type: "artifact",
    slug: "regional-archive-collection",
    title: "Архивная коллекция",
    shortDescription:
      "Собрание документов и визуальных свидетельств истории региона.",
    fullDescription:
      "Коллекция включает описания архивных документов, фотографий и материалов личного происхождения, связанных с местами и событиями атласа.",
    coordinates: null,
    periodFrom: 1800,
    periodTo: null,
    relations: 12,
    sourceType: "archive_document",
    sourceTitle: "Опись региональной архивной коллекции",
  },
] satisfies EntitySeed[];
