import type { AdminEntityView } from "../domain/catalog";

export const seedEntities: AdminEntityView[] = [
  {
    id: "60000000-0000-4000-8000-000000000001",
    type: "settlement",
    slug: "grozny",
    title: { ru: "Грозный", ce: null },
    shortDescription: { ru: "Столица Чеченской Республики", ce: null },
    fullDescription: {
      ru: "Исторический город и столица республики.",
      ce: null,
    },
    coordinates: { latitude: 43.318, longitude: 45.698 },
    periodFrom: null,
    periodTo: null,
    districtId: null,
    status: "published",
    version: 1,
    relationsCount: 128,
    sourcesCount: 67,
    mediaCount: 24,
  },
  {
    id: "60000000-0000-4000-8000-000000000002",
    type: "settlement",
    slug: "nozhay-yurt",
    title: { ru: "Ножай-Юрт", ce: null },
    shortDescription: { ru: "Село в Чеченской Республике", ce: null },
    fullDescription: {
      ru: "Административный центр Ножай-Юртовского района.",
      ce: null,
    },
    coordinates: { latitude: 43.092, longitude: 46.378 },
    periodFrom: null,
    periodTo: null,
    districtId: null,
    status: "draft",
    version: 3,
    relationsCount: 36,
    sourcesCount: 16,
    mediaCount: 7,
  },
  {
    id: "60000000-0000-4000-8000-000000000003",
    type: "person",
    slug: "akhmat-kadyrov",
    title: { ru: "Ахмат-Хаджи Кадыров", ce: null },
    shortDescription: { ru: "Государственный и религиозный деятель", ce: null },
    fullDescription: { ru: "Первый Президент Чеченской Республики.", ce: null },
    coordinates: null,
    periodFrom: 1951,
    periodTo: 2004,
    districtId: null,
    status: "published",
    version: 2,
    relationsCount: 45,
    sourcesCount: 12,
    mediaCount: 8,
  },
];
